Tracer-Cloud/tracer-client

src/config_manager/config.rs
src/main.rs

This function helps validate that a path/file exists and has write permissions.

Added Path validation for Config Manager

---

README.md

[Fixes ](https://linear.app/tracercloud/issue/ENG007-76/improve-tracer-readme)

Readme Update: How to setup Tracer Locally 

---

.github/workflows/build-and-test.yml
Makefile
docker-compose.yml
src/cloud_providers/aws/s3.rs
src/exporters/s3.rs
src/lib.rs

This PR removes localstack as mock for our s3 tests and use real s3 buckets.

Moving s3 tests from localstack to real aws

---

.github/pull_request_template.md
Cargo.lock

add pr template

---

Cargo.lock
installation-script.sh

- Add a new tracer installation script called installation-script.sh
This will allow to download tracer on every EC2 machine just by a command line command

add new tracer installation script

---

.github/workflows/cross-platform-release.yml
Cargo.lock

Update release action for better speed
Add caching strategy for builds in order to reuse dependencies already built

update github actions for faster release

---

Cargo.lock
src/cloud_providers/aws/pricing.rs
src/events/mod.rs
src/exporters/db.rs
src/tracer_client.rs
src/types/aws/pricing.rs

Removed vcpu and memory filters from aws pricing client.
After some investigation we noticed that the memory filter is not precise and leads to bugs in the api request, and more, given the regionCode and the instanceType we are sure about the instance price, with no other filter to be added.

removed vcpu and memory filters

---

installation-script-development.sh

Updates dev installation script to remove calls to frontend api

remove comment out send_event on installation script

---

install-tracer.sh
installation-script-development.sh
installation-script.sh

triggering script update via PR. Removing need for api_key

---

.github/workflows/cross-platform-release-and-assets-upload-on-s3.yml
.github/workflows/cross-platform-release.yml
installation-script-development.sh
installation-script.sh

build binaries for linux arm64 arch. Installation script uses appropriate 

---

Cargo.lock
Cargo.toml
README.md

This Pr Tries to Remove OpenSSL dependencies from the tracer bin

remove features pulling openssl as dependencies. Maybe openssl-probe?

---

deployments/scripts/setup_nextflow_test_env.sh
infrastructure/ec2-tracer-sandbox/main.tf
infrastructure/ec2-tracer-sandbox/script-install-deps.sh
infrastructure/ec2-tracer-sandbox/variables.tf
infrastructure/launch-template/main.tf
infrastructure/launch-template/setup-tracer.sh
infrastructure/modules/ec2_common/main.tf
infrastructure/one-command-infra-provisioning/initialize.sh
infrastructure/one-command-infra-provisioning/main.tf
infrastructure/one-command-infra-provisioning/outputs.tf
src/config_manager/config.rs
src/daemon_communication/client.rs
src/tracer_client.rs
src/utils/debug_log/mod.rs

Isolate SocketFiles in Daemon Communication to TempDirs

---

README.md

Replaced PNG by GIF README.md

---

README.md
installation-script-development.sh

Update README.md with the new installation script link

---

DOCUMENTATION.md
infrastructure/ec2-tracer-sandbox/script-install-deps.sh
infrastructure/ec2-tracer-sandbox/variables.tf
infrastructure/launch-template/setup-tracer.sh
infrastructure/one-command-infra-provisioning/initialize.sh
infrastructure/one-command-infra-provisioning/main.tf
src/lib.rs
src/utils/debug_log/mod.rs

Group Tracer Tmp files 

---

.github/workflows/cross-platform-release-and-assets-upload-on-s3.yml
docs/README.MD
infrastructure/ec2-tracer-sandbox/script-install-deps.sh
infrastructure/launch-template/setup-tracer.sh
infrastructure/one-command-infra-provisioning/initialize.sh
src/extracts/fs/mod.rs
src/extracts/fs/utils.rs
src/extracts/mod.rs
src/lib.rs
src/nextflow_log_watcher.rs
src/tracer_client.rs
src/utils/debug_log/mod.rs

What’s Fixed:
- Group Permissions & Umask: Configured proper group permissions in the infrastructure setup and set the correct umask for the daemon.
- Tracer Info Hang Resolved:
- Optimized log file reading by tracking the last read position instead of reprocessing from the start.
- Implemented non-blocking Nextflow log discovery, ensuring smoother execution without freezes.

Tracer Permissions Fix in Launch Template & Non-Blocking Nextflow Watcher

---

src/extracts/process_watcher.rs
src/types/event/attributes/process.rs

Add aws batch job id, container host and working directory handling when polling process events
Example data with new variables
```
{
"tags": [],
"run_id": "6118fc95-ea1d-40b7-9f17-6ce1ed8edfc3",
"message": "[2025-04-01 18:29:24.556883757 UTC] Tool process: Common-Cleaner",
"run_name": "snowy-wolf-70",
"timestamp": 1743532164,
"attributes": {
"process": {
"job_id": "7fdca217-017f-4da5-a5c1-508b55663bcc", // this is the aws batch job id
"tool_cmd": "java -Xmx15360m -XX:+ExitOnOutOfMemoryError -Dfastqc.threads=4 -Dfastqc.quiet=true -XX:ParallelGCThreads=1 -Djava.awt.headless=true uk.ac.babraham.FastQC.FastQCApplication RAP1_UNINDUCED_REP1_raw.gz",
"tool_pid": "9107",
"tool_name": "Common-Cleaner",
"input_files": [],
"container_id": "ip-172-31-44-168.ec2.internal", // this is the container …
```

add container id and job id, retrieved working dir for processes

---

docker-compose.yml
docs/README.MD
src/events/recorder.rs
src/tracer_client.rs
src/types/cli/mod.rs
src/types/event/mod.rs

Tag Enforcement Setup on Tracer Init

---

src/lib.rs
src/tracer_client.rs

remove Unnecessary Arc from db client

---

migrations/20250409194126_add_process_status_column_and_index.down.sql
migrations/20250409194126_add_process_status_column_and_index.up.sql
src/exporters/db.rs
tests/simple_queries.rs

Adding process status column to database and indexes to reduce query times.
Approximately query times reduced by >95%

Store and insert `process_status` as a separate column

---

.github/workflows/cross-platform-release-and-assets-upload-on-s3.yml

Add binary compilation for amazon linux.
- Instead of using a self hosted runner, that requires costs and at least some checks time to time, i went for an easier compilation inside a docker container. in this way we save cost and it's easier to manage

add compilation to support amazon linux

---

src/cli/nondaemon_commands.rs

Fix clippy

---

.github/workflows/build-and-test.yml
.github/workflows/cross-platform-release.yml

Add the possibility to release for amazon linux when we tag a release

add release for amazon linux

---

integration_tests/tests/common/mod.rs
integration_tests/tests/parallel.rs
integration_tests/tests/simple_queries.rs
src/common/src/event/mod.rs
src/common/src/event/utils.rs
src/extracts/src/process_watcher.rs

flatten event attributes and update tests

---

infrastructure/launch-template/setup-tracer.sh

download tracer client from tracer.cloud

---

Cargo.lock
src/common/Cargo.toml
src/common/src/target_process/mod.rs
src/common/src/target_process/targets_list.rs

Add Processing For Default Tool Display Name

---

deployments/Dockerfile
deployments/tests/Dockerfile
rust-toolchain.toml

bump rust version to 1.86

---

docker-compose.yml
integration_tests/tests/parallel.rs
integration_tests/tests/simple_queries.rs
rust-toolchain.toml
src/common/src/target_process/targets_list.rs

Fix Integrations Test and Add FeatureCounts to TargetList

---

deployments/scripts/setup_nextflow_test_env.sh

remove token based cloning from setup env script as pipeline repo is public

---

.github/workflows/build-and-test.yml
src/cli/tests/common/test_server.rs
src/client/src/config_manager/config.rs
src/client/src/exporters/db.rs
src/daemon/src/daemon.rs

Db secrets are now optional in order to allow people to use the log forwarding service

make db secrets optional

---

installation-script-development.sh

Rollback installation-script-development.sh

---

.github/workflows/build-and-test.yml
Makefile
integration_tests/tests/parallel.rs
integration_tests/tests/simple_queries.rs
src/cli/tests/cli.rs
src/client/src/events/mod.rs
src/client/src/tracer_client.rs
src/cloud_providers/aws/src/pricing.rs

Fixing Cargo Tests.. Removing deps from aws sdk

---

Cargo.lock
src/cli/tests/common/test_server.rs
src/client/src/config_manager/config.rs
src/client/src/params.rs
src/daemon/Cargo.toml
src/daemon/src/daemon.rs

Add new `is-dev` cli argument. if not passed will be by default `true` 
the syntax is : `is-dev true` or `is-dev false`

add is-dev cli argument, default to true

---

src/common/src/target_process/targets_list.rs

Extra Filters To target matching

---

Cargo.lock
src/client/src/exporters/log_forward.rs
src/common/Cargo.toml
src/common/src/target_process/manager.rs
src/common/src/target_process/mod.rs
src/common/src/target_process/targets_list.rs
src/extracts/src/process_watcher.rs

Pr extends the target list and updates the Process watcher to filter events got from ebpf layer before adding to state.

TargetList Extension and ProcessWatcher Changes

---

src/common/src/types/extracts/db.rs

set 0 mem for short lived processes

---

src/common/src/target_process/targets_list.rs
src/common/src/types/event/attributes/process.rs
src/common/src/types/trigger.rs
src/ebpf/rs/types.rs
src/extracts/src/process_watcher.rs
src/extracts/src/process_watcher/mod.rs
src/extracts/src/process_watcher/utils.rs
src/extracts/src/process_watcher/watcher.rs
src/extracts/tests/process_pipeline.rs

tie tracepoint for oom events tracked through ebpf and reconsolidated in process watcher

---

src/client/src/tracer_client.rs
src/extracts/src/ebpf_watcher/handler/process/process_manager.rs
src/extracts/src/ebpf_watcher/watcher.rs

process polling

---

Cargo.lock
Cargo.toml
src/common/Cargo.toml
src/common/src/target_process/mod.rs
src/common/src/target_process/nf_process_list.json
src/common/src/target_process/nf_process_match.rs

https://linear.app/tracercloud/issue/ENG-426/grouped-task-12-known-process-identification-problems-overview
- Introduced `nf_process_match.rs` for matching commands against defined processes using regex patterns.
- Added a new JSON file `nf_process_list.json` containing process definitions and test commands.

Add NextFlow process matching based on regex patterns

---

src/cli/src/nondaemon_commands.rs
src/cli/src/process_command.rs
src/client/src/config_manager/config.rs
src/daemon/src/app.rs
src/daemon/src/daemon.rs

remove the need for config.toml file

---

README.md
installation.sh
src/cli/src/process_command.rs
src/cli/src/utils.rs

Update script to use `sudo`
Print command if tracer is run without `sudo`
It also tell the full command to run with sudo (see screenshot)

improve installation

---

.github/workflows/enforce-dev-to-main.yml
README.md
installation-script-development.sh
installation.sh
src/extracts/src/ebpf_watcher/watcher.rs

dev to main

---

src/cli/src/nondaemon_commands.rs

Update info box

---

.github/workflows/cross-platform-release.yml
installation.sh
src/cli/src/nondaemon_commands.rs
src/cli/src/process_command.rs
src/cli/src/utils.rs
src/client/src/tracer_client.rs
src/daemon/src/client.rs
src/extracts/src/ebpf_watcher/handler/process/process_utils.rs
src/extracts/src/ebpf_watcher/watcher.rs

Installation improvements

---

deployments/scripts/setup_nextflow_test_env.sh
infrastructure/ec2-tracer-sandbox/script-install-deps.sh
infrastructure/launch-template/main.tf

Update Tracer AMI

---

src/tracer/src/client/tracer_client.rs
src/tracer/src/extracts/ebpf_watcher/handler/trigger/trigger_processor.rs
src/tracer/src/extracts/ebpf_watcher/watcher.rs

https://linear.app/tracercloud/issue/ENG-463/better-error-handling-on-ebpf-loading

feat: add non ebpf support to linux

---

README.md
installation-script-development.sh
installation-script.sh
installation.sh
src/tracer/src/client/config_manager/config.rs
src/tracer/src/client/config_manager/mod.rs
src/tracer/src/common/types/analytics.rs
src/tracer/src/common/types/mod.rs
src/tracer/src/daemon/daemon_run.rs
src/tracer/src/process_command.rs
src/tracer/src/utils.rs

add send analytics event to script installations

---

.devcontainer/Dockerfile
deployments/tests/Dockerfile
docs/EBPF.MD

Removed references to aya

---

.github/workflows/cross-platform-release.yml
src/tracer/src/extracts/process/process_manager/handlers/process_starts.rs
src/tracer/src/extracts/process/process_manager/matcher.rs

remove parent process check

---

binary-installer.sh
src/tracer/src/daemon/daemon_run.rs
src/tracer/src/process_command.rs
src/tracer/src/utils/mod.rs

emit event on tracer cli checks the user_id before getting to env fallback

---

installation-script.sh
src/tracer/src/nondaemon_commands.rs

auto release on merge on main

---

src/tracer/src/common/target_process/yml_rules/tracer.rules.yml

Some rules got lost when converting default_rules.json to yaml. I used this script to redo the conversion: https://gist.github.com/jdidion/3b5b713ed52ebdecef93cade4c713bb6
ENG-503
Updated `tracer.rules.yml`
None

Add back rules that got lost in json->yaml conversion

---

src/tracer/build.rs
src/tracer/src/common/target_process/target_manager.rs
src/tracer/src/common/target_process/yml_rules/tracer.exclude.yml

Added exclusion rules in `tracer.exclude.yml`

add exclusion rules

---

src/tracer/src/common/target_process/target_manager.rs
src/tracer/src/common/target_process/yml_rules/tracer.exclude.yml
src/tracer/tests/assets/nfcore_rnaseq_process_list.json

Removing version exclude because core part of pipeline testing

---

src/tracer/src/process_identification/target_process/target_manager.rs

just remove some duplicate code

small refactor

---

src/tracer/src/client/tracer_client.rs

Move processes into context - Sentry

---

migrations/20250624170854_query_statistics_tz.down.sql
migrations/20250624170854_query_statistics_tz.up.sql
scripts/migrate.sh
scripts/rollback.sh

Migration Files For Database Cron Used For Internal DB Perf Dashboards

---

README.md

Update README.md to remove table of contents

---

docs/EXAMPLES.md

Update pipeline URL

---

migrations/20250625172007_add_exit_reason_to_runs_aggregations.down.sql
migrations/20250625172007_add_exit_reason_to_runs_aggregations.up.sql
migrations/20250625172055_create_new_aggregate_view_for_tools.down.sql
migrations/20250625172055_create_new_aggregate_view_for_tools.up.sql
migrations/20250627163909_create_tools_events_table.down.sql
migrations/20250627163909_create_tools_events_table.up.sql
src/ebpf/rs/types.rs
src/tracer/src/extracts/ebpf_watcher/watcher.rs

Migrations to add an aggregate view built with triggers in real time, to simulate the incremental views and increase the dashboards usability with faster queries.
Will be built a new database architecture to handle this better

improve database performances

---

src/tracer/src/daemon/server/daemon_server.rs
src/tracer/src/daemon/server/process_monitor.rs

Perform refactorings suggested in Github issue #106

---

.gitignore
src/tracer-installer/src/checks/environment.rs
src/tracer-installer/src/checks/mod.rs
src/tracer-installer/src/installer/install.rs
src/tracer-installer/src/main.rs
src/tracer/src/utils/analytics/mod.rs
src/tracer/src/utils/env.rs
src/tracer/src/utils/mod.rs

Adds Environment Detection To Events analytics metadata

---

.github/dependabot.yml

- Target main branch for dependabot updates
- Add docker and git submodules targets for dependabot

chore: update dependabot configuration to target main branch and add support for Docker and Git submodules

---

Cargo.lock
Cargo.toml
src/tracer/Cargo.toml
src/tracer/src/cli/handlers/info.rs
src/tracer/src/client/events/mod.rs
src/tracer/src/client/tracer_client.rs
src/tracer/src/cloud_providers/aws/config.rs
src/tracer/src/cloud_providers/aws/ec2.rs
src/tracer/src/cloud_providers/aws/mod.rs
src/tracer/src/cloud_providers/aws/pricing.rs
src/tracer/src/cloud_providers/aws/pricing/api.rs
src/tracer/src/cloud_providers/aws/pricing/aws.rs
src/tracer/src/cloud_providers/aws/pricing/filtering/ec2_matcher.rs
src/tracer/src/cloud_providers/aws/pricing/filtering/mod.rs
src/tracer/src/cloud_providers/aws/pricing/mod.rs
src/tracer/src/cloud_providers/aws/s3.rs
src/tracer/src/cloud_providers/aws/secrets.rs
src/tracer/src/cloud_providers/aws/types/pricing.rs
src/tracer/src/cloud_providers/aws/types/pricing/api.rs
src/tracer/src/cloud_providers/aws/types/pricing/aws.rs
src/tracer/src/cloud_providers/aws/types/pricing/mod.rs
src/tracer/src/config/defaults.rs
src/tracer/src/daemon/structs.rs
src/tracer/src/process_identification/types/current_run.rs
src/tracer/src/process_identification/types/event/attributes/system_metrics.rs

Adds EC2 + EBS Cost Estimation for Pipeline Runs
- Adds PipelineCostSummary to pipeline run metadata
- Calculates cost_per_minute and estimated_total since run start
- Displays cost in tracer info output
- Embeds cost metadata in NewRun event logs
- API Based Pricing Integration as fallback when AWS credential isn't configured

Price Tracking Impl

---

src/tracer/src/process_identification/target_process/yml_rules/tracer.rules.yml

remove duplicate multiqc rule

---

migrations/20250715155400_add_exit_code_to_tool_aggregations.up.sql
migrations/20250715155800_add_exit_code_to_runs_aggregation.up.sql

Fix migrations

---

src/tracer/src/extracts/process/process_manager/handlers/process_starts.rs

remove prefiltering rules for now

---

src/tracer/src/cli/handlers/init/arguments.rs

Added some better error messages when init fails with an error due to reading input from the terminal.

Add better errors for init failures

---

migrations/20250715155400_add_exit_code_to_tool_aggregations.up.sql
migrations/20250715155800_add_exit_code_to_runs_aggregation.up.sql

`curl -sSL https://install.tracer.cloud | CLI_BRANCH="fix-triggers" sh && source ~/.bashrc && source ~/.zshrc`
`curl -sSL https://install.tracer.cloud | INS_BRANCH="fix-triggers" sh && source ~/.bashrc && source ~/.zshrc`

Fix run and tool aggregation triggers

---

migrations/20250715155400_add_exit_code_to_tool_aggregations.down.sql
migrations/20250715155800_add_exit_code_to_runs_aggregation.down.sql
migrations/20250715155800_add_exit_code_to_runs_aggregation.up.sql

Fix migrations 4

---

Cargo.lock
src/tracer/Cargo.toml
src/tracer/src/cli/handlers/init/arguments.rs
src/tracer/src/cli/handlers/init/handler.rs
src/tracer/src/cli/process_daemon_command.rs
src/tracer/src/client/exporters/client_export_manager.rs
src/tracer/src/client/exporters/log_forward.rs
src/tracer/src/daemon/handlers/info.rs
src/tracer/src/daemon/handlers/terminate.rs
src/tracer/src/daemon/server/daemon_server.rs
src/tracer/src/daemon/server/process_monitor.rs

`curl -sSL https://install.tracer.cloud | INS_BRANCH="branch_name" sh && source ~/.bashrc && source ~/.zshrc` 
Simplified our daemon server loop, removed the code that was blocking. @mountwo23 will write a new retry method that is non blocking

fix submit data WILL MERGE ONCE WORKING - BAEKHAN

---

src/tracer/src/extracts/metrics/system_metrics_collector.rs
src/tracer/src/process_identification/types/event/attributes/system_metrics.rs

Add total disk space to system metric

---

src/tracer/src/cli/handlers/init/arguments.rs
src/tracer/src/utils/env.rs

`curl -sSL https://install.tracer.cloud | INS_BRANCH="branch_name" sh && source ~/.bashrc && source ~/.zshrc` 
Command changes to `sudo -E tracer init`

chore: attach tracer user id to pipeline run

---

security/policy.md

Add security policy

---

.github/workflows/semgrep.yml
src/tracer/src/client/exporters/db.rs

remove upload from diff scan

---

src/tracer/src/cli/commands.rs
src/tracer/src/cli/handlers/cleanup_port.rs
src/tracer/src/cli/handlers/mod.rs
src/tracer/src/cli/handlers/terminate.rs
src/tracer/src/cli/process_command.rs
src/tracer/src/cli/process_daemon_command.rs

Fix cleanup port

---

Cargo.lock
Cargo.toml
src/ebpf/Cargo.toml
src/ebpf/rs/ebpf_trigger.rs
src/tracer/Cargo.toml
src/tracer/src/cli/commands.rs
src/tracer/src/cli/handlers/info.rs
src/tracer/src/cli/handlers/init/handler.rs
src/tracer/src/cli/handlers/test/arguments.rs
src/tracer/src/cli/handlers/test/handler.rs
src/tracer/src/cli/process_daemon_command.rs
src/tracer/src/daemon/handlers/info.rs
src/tracer/src/daemon/structs.rs
src/tracer/src/extracts/process/process_manager/handlers/process_starts.rs
src/tracer/src/extracts/process/process_manager/manager.rs
src/tracer/src/extracts/process/process_manager/state.rs
src/tracer/src/extracts/process/types/process_state.rs
src/tracer/src/extracts/process_watcher/watcher.rs
src/tracer/src/process_identification/target_pipeline/parser/pipeline.rs
src/tracer/src/process_identification/target_pipeline/parser/yaml_rules_parser.rs
src/tracer/src/process_identification/target_pipeline/pipeline_manager.rs
src/tracer/src/process_identification/target_pipeline/yml_rules/tracer.pipelines.yml
src/tracer/src/process_identification/target_process/parser/conditions.rs
src/tracer/src/process_identification/target_process/parser/yaml_rules_parser.rs
src/tracer/src/process_identification/target_process/target_manager.rs
src/tracer/src/process_identification/target_process/target_match.rs
src/tracer/src/process_identification/target_process/yml_rules/tracer.rules.yml
src/tracer/src/process_identification/utils.rs
src/tracer/src/utils/cli/box_formatter.rs
src/tracer/src/utils/workdir.rs

Use parent task PID to differentiate tasks in pipeline matcher

---

src/tracer/src/client/tracer_client.rs
src/tracer/src/utils/analytics/mod.rs
src/tracer/src/utils/env.rs

add timeout to ec2 environment detection

---

src/tracer/src/cli/handlers/init/arguments.rs
src/tracer/src/cli/handlers/test/arguments.rs

remove tracer test functionality to run user pipelines/tools

---

.github/workflows/build-and-test.yml
src/tracer-installer/src/installer/install.rs
src/tracer/src/constants.rs
src/tracer/src/extracts/process/extract_process_data.rs

fix tool_id generation

---

.github/workflows/semgrep.yml

enable managed semgrep

---

src/tracer-installer/src/sentry.rs

Remove sentry debugging

---

src/tracer/src/cli/handlers/demo/pipeline/pixi.rs

fixing pixi

---

Cargo.lock
src/tracer/src/cli/handlers/info.rs
src/tracer/src/cli/handlers/init/arguments/resolver.rs
src/tracer/src/cli/handlers/init/handler.rs
src/tracer/src/cli/handlers/init/setup/daemon_spawn.rs
src/tracer/src/daemon/structs/pipeline_data.rs
src/tracer/src/process_identification/types/pipeline_tags.rs

tracer info with the email field

add email to tags

---

src/tracer/src/constants.rs

Update event forward endpoint for development environment
